# Interactive ZSH configuration script
#
ZSH_CONFIG_DIR="$(dirname "${${(%):-%N}:A}")"
ZSH_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
ZSH_DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/zsh"

mkdir -p "$ZSH_DATA_DIR"

# Load settings (cached for speed)
if [[ ! -s "$ZSH_CACHE_DIR/config.zsh" ]]; then
  source "$ZSH_CONFIG_DIR/lib/init.zsh"
fi
source "$ZSH_CACHE_DIR/config.zsh"

