#!/bin/sh
# Bash RC, loaded for interactive non-login shells

# Load environment variables
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
[[ -f "$XDG_CONFIG_HOME/profile.sh" ]] && . "$XDG_CONFIG_HOME/profile.sh"

# If the shell is not interactive, quit
[[ -z "$PS1" ]] && return

#{INCLUDE bash_theme.sh}
#{REMOTE DELETE}
BASH_CONFIG_DIR="$(dirname "$(readlink -f "$(readlink "${BASH_SOURCE[0]}")")")"
. "$BASH_CONFIG_DIR/bash_theme.sh"
#{/REMOTE DELETE}

# Sensible bash defaults

# Update window size after every command
shopt -s checkwinsize
# Turn on recursive globbing (enables ** to recurse all directories)
shopt -s globstar 2> /dev/null
# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

## SMARTER TAB-COMPLETION (Readline bindings) ##

# Perform file completion in a case insensitive fashion
bind "set completion-ignore-case on"
# Treat hyphens and underscores as equivalent
bind "set completion-map-case on"
# Display matches for ambiguous patterns at first tab press
bind "set show-all-if-ambiguous on"
# Immediately add a trailing slash when autocompleting symlinks to directories
bind "set mark-symlinked-directories on"

## SANE HISTORY DEFAULTS ##

# append to the history file, don't overwrite it
shopt -s histappend
# Save multi-line commands as one command
shopt -s cmdhist
# don't add duplicates
export HISTCONTROL=ignoreboth:erasedups
# Don't record some commands
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"
# set huge history length
HISTSIZE=500000
HISTFILESIZE=100000
# Use standard ISO 8601 timestamp: %Y-%m-%d %H:%M:%S
HISTTIMEFORMAT='%F %T '
# Append each history line after each executed command
PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# Enable incremental history search with up/down arrows
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
bind '"\e[C": forward-char'
bind '"\e[D": backward-char'

## ALIASES ##

# file listing
alias ll='ls -alh'
alias la='ls -A'
alias l='ls -CFlh'

# Colored less and grep
export LESS='-g -i -M -R -S -w -z-4'
export GREP_COLOR='38;5;202'
alias grep="grep --color=auto"

# Colored & human friendly system commands
alias ip="ip -c"
alias df='df -PTh -x tmpfs -x devtmpfs -x squashfs -x overlay | column -t'
alias du.='du -hx --max-depth=1'
alias free="free -h"

## BETTER DIRECTORY NAVIGATION ##

# Prepend cd to directory names automatically
shopt -s autocd 2> /dev/null
# Correct spelling errors during tab-completion
shopt -s dirspell 2> /dev/null
# Correct spelling errors in arguments supplied to cd
shopt -s cdspell 2> /dev/null

# This defines where cd looks for targets
# Add the directories you want to have fast access to, separated by colon
# Ex: CDPATH=".:~:~/projects" will look for targets in the current working directory, in home and in the ~/projects folder
CDPATH=".:~"

